### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by faern**
Maybe not the most comprehensive documentation on earth. But way better than before. And most importantly IMO: The protocol is specified in the documentation, and not only the code.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/5)

### CODE REVIEW

**Review by dlon — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/5#-:-MWQ5iOU90nBM_awbThG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/5)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/5#-MWQ6QVgCbBaYujucmTA:-MWQ0HTxEk1Cw1Wo3m9S:b-vt4v92) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/b1520b1adbf0d7c7f932b7089a41838dae970971/README.md#L13)):*
> ```Markdown
>   Rust programs. The UDP socket is connected to the peer address of the first incoming
>   datagram. So one [`Udp2Tcp`] instance can handle traffic from a single peer only.
> * `tcp2udp` - Listens to TCP and translates any incoming data to datagrams and forward them
> ```

Nitpick: Doesn't "listens to TCP" sound slightly strange? I guess it could simply say "Translates incoming TCP data to UDP datagrams [...]".

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)

___
*[README.md, line 13 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/5#-MWQ6QVgCbBaYujucmTA:-MWTdHQ3BcIMRyYboGOP:b7y0suy) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/b1520b1adbf0d7c7f932b7089a41838dae970971/README.md#L13)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nitpick: Doesn't "listens to TCP" sound slightly strange? I guess it could simply say "Translates incoming TCP data to UDP datagrams [...]".
</blockquote></details>

Yeah. Valid feedback. I did some changes.

**Review by dlon — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)

**Pull request merged**
