### PR TITLE
Add Github Actions to check formatting, linting etc

### PR DESCRIPTION
**Pull request by faern**
This repository is slowly getting more serious/stable. But we had no CI on it at all. So I added this Github Actions config to automatically check:

* Formatting
* Strict linting with clippy
* Check `Cargo.lock` for known vulnerabilities with `cargo audit`
* Build and run tests

I did not feel like the project was large enough to justify splitting it into multiple workflows that trigger on different path changes. Everything runs pretty fast anyway, so we can run everything on every push for now IMO.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)

### CODE REVIEW

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @dlon and @jvff)

___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_23Js5Uq0x7uAwzdP:-MW_23Js5Uq0x7uAwzdQ:b-dnhp9r) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v2
>       - run: cargo fmt -- --check
> ```

I honestly don't know if there is any benefit of using the dedicated `cargo` action that we use for actually building and testing further down. The `actions-rs/cargo@v1` one. Do you see any reason to use one or the other?
___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2Erh9zC00_u4vu3a:-MW_2Erh9zC00_u4vu3b:b-l3inuv) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v2
>       - run: cargo fmt -- --check
> ```

I'm just issuing cargo commands directly here without even installing the toolchain... It works... I tried `- run: cargo --version` and found out that `ubuntu-latest` seem to come with Rust 1.50 already. Not sure if it will always come with latest stable or what's up here. Is it safe to ignore explicitly installing latest stable and rely on Github Actions to provide it? :thinking: 
___
*[.github/workflows/ci.yml, line 23 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_1sHd7hm8MIcf4wns:-MW_1sHd7hm8MIcf4wnt:b-vgxat1) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L23)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v2
>       - run: cargo audit --deny-warnings
> ```

There is a special action for this. But it has a bug where it does not respect a checked in `Cargo.lock`. Making it kind of useless for this repository I think: https://github.com/actions-rs/audit-check/issues/163#issuecomment-805942971
___
*[.github/workflows/ci.yml, line 44 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2u-q7PBJqjjdDiaR:-MW_2u-q7PBJqjjdDiaS:b9aqs2p) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L44)):*
> ```YAML
>           # MSRV. Not considered breaking when this has to be bumped.
>           # But should be mentioned in the changelog.
>           - 1.43.0
> ```

I'm only checking this matrix of toolchains on Linux. I decided to only test `stable` on macOS + Windows. Do you agree with that decision or is it worth all the extra build minutes to run everything everywhere? I think this should be enough. This crate does almost nothing platform specific.

**Review by jvff — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon and @faern)

___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_23Js5Uq0x7uAwzdP:-MW_6yg3Ag7KxPCz5_Mc:b-tx7q2n) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I honestly don't know if there is any benefit of using the dedicated `cargo` action that we use for actually building and testing further down. The `actions-rs/cargo@v1` one. Do you see any reason to use one or the other?
</blockquote></details>

The benefit I can think of is to see more quickly that formatting failed. :thinking: 
___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2Erh9zC00_u4vu3a:-MW_7DS20yfqMw8shEh4:bmhih0c) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm just issuing cargo commands directly here without even installing the toolchain... It works... I tried `- run: cargo --version` and found out that `ubuntu-latest` seem to come with Rust 1.50 already. Not sure if it will always come with latest stable or what's up here. Is it safe to ignore explicitly installing latest stable and rely on Github Actions to provide it? :thinking: 
</blockquote></details>

One thing to be aware of is if we end up needing any nightly `rustfmt` rules.
___
*[.github/workflows/ci.yml, line 44 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2u-q7PBJqjjdDiaR:-MW_8OGu1mfQwh572P-R:b-wpune1) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm only checking this matrix of toolchains on Linux. I decided to only test `stable` on macOS + Windows. Do you agree with that decision or is it worth all the extra build minutes to run everything everywhere? I think this should be enough. This crate does almost nothing platform specific.
</blockquote></details>

Yeah, that makes sense. I really like the idea of adding the MSRV here, should we add that to the `mullvadvpn-app` repo as well?
___
*[.github/workflows/ci.yml, line 31 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_88VV2GV1Qp2IIMQh:-MW_88VV2GV1Qp2IIMQi:b-4mt7b) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L31)):*
> ```YAML
>       - uses: actions-rs/clippy-check@v1
>         with:
>           token: ${{ secrets.GITHUB_TOKEN }}
> ```

Is the token needed for this job?
___
*[.github/workflows/ci.yml, line 104 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_9tCF0Mve-6fxRQwA:-MW_9tCF0Mve-6fxRQwB:bsig686) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L104)):*
> ```YAML
>         uses: actions-rs/cargo@v1
>         with:
>           command: test
> ```

Missing a new line at the end I think.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 4 unresolved discussions (waiting on @dlon, @faern, and @jvff)

___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2Erh9zC00_u4vu3a:-MW_G7pR7fwXGurbGV34:byph76i) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

One thing to be aware of is if we end up needing any nightly `rustfmt` rules.
</blockquote></details>

This crate won't use nigthly formatting. I want to move everything more towards the stable formatter and not the other way around.
___
*[.github/workflows/ci.yml, line 44 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2u-q7PBJqjjdDiaR:-MW_GXBm56yx6VagplLX:bw1gf9o) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Yeah, that makes sense. I really like the idea of adding the MSRV here, should we add that to the `mullvadvpn-app` repo as well?
</blockquote></details>

I don't think that's as relevant. Because that's not a library, that's a program. So our main app does not need to adhere to semver or anything. Not that I count MSRV breaking as semver breaking anyway. But you get the idea. The app is not consumed as a rust crate by anyone else.
___
*[.github/workflows/ci.yml, line 31 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_88VV2GV1Qp2IIMQh:-MW_GDvu0zoug4ozNPd1:bbebits) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Is the token needed for this job?
</blockquote></details>

Yes. My understanding is that the token is what allows the job to post extra status updates. These: https://github.com/mullvad/udp-over-tcp/runs/2186534091?check_suite_focus=true

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon, @faern, and @jvff)

___
*[.github/workflows/ci.yml, line 17 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_23Js5Uq0x7uAwzdP:-MW_HMxV9pLJ1yN94ERD:bqcam3d) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L17)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

The benefit I can think of is to see more quickly that formatting failed. :thinking: 
</blockquote></details>

Oops, nevermind. I had misunderstood the question :sweat_smile: 

No difference to me, either option is fine :thinking:

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[.github/workflows/ci.yml, line 44 at r1](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_2u-q7PBJqjjdDiaR:-MW_Hvw_BAHMO0s2a-9M:b-4dqmz3) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/576758b59b73ee13ff300eb29df95c055f49d785/.github/workflows/ci.yml#L44)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I don't think that's as relevant. Because that's not a library, that's a program. So our main app does not need to adhere to semver or anything. Not that I count MSRV breaking as semver breaking anyway. But you get the idea. The app is not consumed as a rust crate by anyone else.
</blockquote></details>

Yep, that makes sense :ok_hand:

**Review by jvff — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 1 unresolved discussion (waiting on @dlon and @faern)

___
*[.github/workflows/ci.yml, line 31 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_88VV2GV1Qp2IIMQh:-MW_IABh92Zu7nRdZfh4:b-xjifmz) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L31)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes. My understanding is that the token is what allows the job to post extra status updates. These: https://github.com/mullvad/udp-over-tcp/runs/2186534091?check_suite_focus=true
</blockquote></details>

Oh, wow. That's a cool feature!

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: all files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[.github/workflows/ci.yml, line 14 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWcipX7BXq9UEV1unbe:-MWcipX7BXq9UEV1unbf:b-e1yzhj) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L14)):*
> ```YAML
> jobs:
>   format:
>     runs-on: ubuntu-latest
> ```

The earlier discussion disappeared, but I think it would be a good idea to install the stable toolchain here. If it's already included, then it won't save any time not to anyway.
___
*[.github/workflows/ci.yml, line 23 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWciNpL2xKvK1rQ2_Ip:-MWcbYgZE5do5cGSoBEK:begd2ux) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L23)):*
> ```YAML
>     steps:
>       - uses: actions/checkout@v2
>       - run: cargo audit --deny-warnings
> ```

Nit: There's a warning about `--deny-warnings` being deprecated in favor of `--deny warnings`.
___
*[.github/workflows/ci.yml, line 34 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWclnWRDgYSdo2WfggN:-MWclnWRDgYSdo2WfggO:b-x19dgx) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L34)):*
> ```YAML
> 
>   test-linux:
>     runs-on: ubuntu-latest
> ```

You could combine this with the jobs below:

```yml
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [macos-latest, windows-latest, ubuntu-latest]
    rust: [stable]
    include:
      - os: ubuntu-latest
        rust:
          - beta
          - nightly
          # MSRV. Not considered breaking when this has to be bumped.
          # But should be mentioned in the changelog.
          - 1.43.0
```

If my reading of [this](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) is correct.

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dlon and @jvff)

___
*[.github/workflows/ci.yml, line 14 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWcipX7BXq9UEV1unbe:-MWdgXyB8vqOcrEE9GLR:b-6quakg) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L14)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The earlier discussion disappeared, but I think it would be a good idea to install the stable toolchain here. If it's already included, then it won't save any time not to anyway.
</blockquote></details>

I agree. I came to the same conclusion after thinking about it for a while. We should not assume much about what's on the original images. Also, installing a toolchain that already exists is super fast. Thanks. I will experiment with it soon!
___
*[.github/workflows/ci.yml, line 23 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWciNpL2xKvK1rQ2_Ip:-MWdggG-1fgeHXxGbkEX:b-4on3p) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L23)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Nit: There's a warning about `--deny-warnings` being deprecated in favor of `--deny warnings`.
</blockquote></details>

Aah. I missed that. I had an older version of `cargo-audit` locally so the deprecation warning did not show up on my computer :+1:
___
*[.github/workflows/ci.yml, line 34 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWclnWRDgYSdo2WfggN:-MWdgxCa2kTjC5hhSO4I:b-rvc4qf) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L34)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

You could combine this with the jobs below:

```yml
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [macos-latest, windows-latest, ubuntu-latest]
    rust: [stable]
    include:
      - os: ubuntu-latest
        rust:
          - beta
          - nightly
          # MSRV. Not considered breaking when this has to be bumped.
          # But should be mentioned in the changelog.
          - 1.43.0
```

If my reading of [this](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) is correct.
</blockquote></details>

Nice find. The question is if we want to. That's a lot of building. But yeah. For this small repo that likely won't see that much change long term it might make sense maybe.
___
*[.github/workflows/ci.yml, line 104 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MW_9tCF0Mve-6fxRQwA:-MWdgsVN7uOb_PqGX1dH:b-896fix) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L104)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Missing a new line at the end I think.
</blockquote></details>

Done.
___
*[.github/workflows/ci.yml, line 13 at r3](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWdhkJtECXL639LPVle:-MWdhkJtECXL639LPVlf:bamqzmv) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/22ec69d13dada47ce4d9151eccd683a59f74f9d6/.github/workflows/ci.yml#L13)):*
I rolled all of these checks into one job. Way less repetition of similar steps.... But I realize now this has downsides. In the PR the check now just shows up as:

> Build and test / meta (push) failed

So you can't see directly form the PR what failed. I will split these again.
___
*[.github/workflows/ci.yml, line 65 at r3](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWdhdZg5w4-atD83K3z:-MWdhdZh8LZZEJH-Fx4j:by549hy) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/22ec69d13dada47ce4d9151eccd683a59f74f9d6/.github/workflows/ci.yml#L65)):*
> ```YAML
>           profile: minimal
>           toolchain: ${{ matrix.rust }}
>           default: true
> ```

Felt better to make it set the default toolchain than just overriding for one directory?

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dlon and @jvff)

___
*[.github/workflows/ci.yml, line 34 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWclnWRDgYSdo2WfggN:-MWdjWPOCAg4NHZxQkM1:bpdaahq) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L34)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Nice find. The question is if we want to. That's a lot of building. But yeah. For this small repo that likely won't see that much change long term it might make sense maybe.
</blockquote></details>

Aaaah. I did not read carefully enough. You can still make it use different sets of Rust versions per OS. Nice

**Review by faern — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @dlon and @jvff)

___
*[.github/workflows/ci.yml, line 34 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWclnWRDgYSdo2WfggN:-MWdy60W1JPupuvMllK0:bu6bfi4) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L34)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Aaaah. I did not read carefully enough. You can still make it use different sets of Rust versions per OS. Nice
</blockquote></details>

I could not make it work exactly as you proposed. Does not look like you can use lists like that under the `include` feature. So I had to specify nightly and MSRV separately as you can see. But should be fine. Still saved a lot of repetition from not repeating the steps in the build.

I opted to run stable + beta on all platforms. This crate is still very cheap to run in CI, and would be nice if we could catch something before it reaches stable if there ever is any issue.

**Review by jvff — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-:-MWe-6Rf-8fe3VyeeliS:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon and @faern)

**Review by dlon — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-:-MWcgt6J7lDfCZvl8dsu:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[.github/workflows/ci.yml, line 34 at r2](https://reviewable.io/reviews/mullvad/udp-over-tcp/9#-MWclnWRDgYSdo2WfggN:-MWe--ge3_XBswMokGEx:bo5cpot) ([raw file](https://github.com/mullvad/udp-over-tcp/blob/6f68e5add991e9f0f9ae525bd243ea3af4a319d7/.github/workflows/ci.yml#L34)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I could not make it work exactly as you proposed. Does not look like you can use lists like that under the `include` feature. So I had to specify nightly and MSRV separately as you can see. But should be fine. Still saved a lot of repetition from not repeating the steps in the build.

I opted to run stable + beta on all platforms. This crate is still very cheap to run in CI, and would be nice if we could catch something before it reaches stable if there ever is any issue.
</blockquote></details>

Nice :)

**Review by jvff — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/udp-over-tcp/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faern)

**Pull request merged**
